/**
 * 애플리케이션 에러에서 사용하는 코드 유형
 */
export const ErrorCode = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    R2_TEMPLATE_NOT_FOUND: 'R2_TEMPLATE_NOT_FOUND',
    R2_TEMPLATE_DELETE_FAILED: 'R2_TEMPLATE_DELETE_FAILED',
    R2_TEMPLATE_UPDATE_FAILED_NO_TARGET: 'R2_TEMPLATE_UPDATE_FAILED_NO_TARGET',
    R2_TEMPLATE_UPDATE_FAILED_ALREADY_EXIST:
        'R2_TEMPLATE_UPDATE_FAILED_ALREADY_EXIST',
    R2_TEMPLATE_CREATE_FAILED_ALREADY_EXIST:
        'R2_TEMPLATE_CREATE_FAILED_ALREADY_EXIST',
    INVALID_PARAM: 'INVALID_PARAM',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
